### PR TITLE
Require `exactOptionalPropertyTypes` for conformance

### PR DESCRIPTION
**Pull request by chriskrycho**
Per discussion at #5: this helps libraries guarantee compatibility with downstream code.

### CODE REVIEW

**Comment by chriskrycho** [comment]
cc. @tjjfvi, @dfreeman, @jamescdavis

**Comment by tjjfvi** [comment]
Might be worth adding a mention of it [here](https://github.com/typed-ember/semver/blob/a46d9a9181bebebbac18f03c96d48b806ba952a5/content/_index.md#conformance) and [here](https://github.com/typed-ember/semver/blob/a46d9a9181bebebbac18f03c96d48b806ba952a5/content/_index.md#strictness) to parallel `noUncheckedIndexedAccess`

**Comment by chriskrycho** [comment]
Ah, great point, will update shortly. Thank you!

**Comment by chriskrycho** [comment]
“Shortly” apparently meant “a year and a half later” but so it goes. I'm updating it now! 😂

**Pull request merged**
